# Site settings
author: Jared Striplin
title: Becoming a developer
header-img: img/home-bg.png
email: jaredjames2020@gmail.com
copyright_name: Jared Striplin
description: > # this means to ignore newlines until "baseurl:"
  Things I learned along the way
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jaredjames2020

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
